mutation register(
 $input: RegisterInput!
) {
  registerUser(input: $input) {
    code,
    success,
    message,
    user{
      id
      name
      surname
      email
      createdAt
      token
    }
  }
}